// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** Category */
export interface Category {
	/** the main id field */
	id: string;
	/** The Domain name */
	domain: string;
	/** If the category is a "sub category", the id_parent contains the id of the Category container */
	id_parent: string;
	/** User that created this category (and it is defined as 'owner') */
	id_owner: string;
	/** A true / false flag defining if the current category is actually a folder */
	is_folder: boolean;
	/** Category name */
	title: string;
	/** Category description */
	description: string;
	/** Category image id */
	image: string;
	/** Category slug */
	slug: string;
	/** If the category is visible */
	visible: boolean;
	/** This is a top category */
	top: boolean;
	/** tags for the type */
	modules: string[];
}

/** CategoryTreeItem */
export interface CategoryTreeItem {
	/** the main id field */
	id: string;
	/** If the category is a "sub category", the id_parent contains the id of the Category container */
	id_parent: string;
	/** User that created this category (and it is defined as 'owner') */
	id_owner: string;
	/** A true / false flag defining if the current category is actually a folder */
	is_folder: boolean;
	/**  */
	top: boolean;
	/** Category name */
	title: string;
	/** Category description */
	description: string;
	/** Category image */
	image: string;
	/** the children of this Tree Item */
	children: CategoryTreeItem[];
	/** Slug */
	slug: string;
	/** Flag T/F for category visibility */
	visible: boolean;
	/** Category modules */
	modules?: string[];
}

/** CategorySmallItem */
export interface CategorySmallItem {
	/** the main id field */
	id: string;
	/** Category name */
	title: string;
	/** Category description */
	description: string;
	/** Category image */
	image: string;
}

